apiVersion: v1
kind: PersistentVolume
metadata:
  name: document-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /root/ws/Documents
    type: DirectoryOrCreate