apiVersion: v1
kind: PersistentVolume
metadata:
  name: exception-files-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /root/ws/ExceptionFiles
    type: DirectoryOrCreate