apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3306
  selector:
    app: mysql-pod
  type: LoadBalancer
