apiVersion: v1
kind: Service
metadata:
  name: apigateway-core-service
spec:
  selector:
    app: apigateway-core-pod
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 80
  type: LoadBalancer
