apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-performance-pod
  labels:
    app: employee-performance-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-performance-pod
  template:
    metadata:
      labels:
        app: employee-performance-pod
    spec:
      containers:
        - name: employee-performance
          image: istiyaqmi9/ems_employeeperformance:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
