apiVersion: v1
kind: Service
metadata:
  name: apigateway-boot-service
spec:
  selector:
    app: apigateway-boot-pod
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer